server:
  port: 8081

spring:
  application:
    name: registration-service
  datasource:
    url: jdbc:mysql://localhost:3306/shopease?createDatabaseIfNotExist=true
    username: root
    password: vvvvvvvv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  file:
    name: logs/registration-service.log
  level:
    root: INFO
    com.shopease: DEBUG 