server:
  port: 8086
  tomcat:
    connection-timeout: 20000
    max-keep-alive-requests: 100
    keep-alive-timeout: 20000
    max-connections: 8192
    accept-count: 100
    threads:
      max: 200
      min-spare: 10
    socket:
      so-keep-alive: true
      so-timeout: 20000
      tcp-no-delay: true
  

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/shopease?createDatabaseIfNotExist=true
    username: root
    password: vvvvvvvv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.shopease.product: DEBUG
  file:
    name: logs/product-service.log
    max-size: 10MB
    max-history: 10 