server:
  port: 8087

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/shopease?createDatabaseIfNotExist=true
    username: root
    password: vvvvvvvv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.shopease.cart: DEBUG
  file:
    name: logs/cart-service.log
    max-size: 10MB
    max-history: 10 