server:
  port: 8082

spring:
  application:
    name: login-service
  datasource:
    url: jdbc:mysql://localhost:3306/shopease?createDatabaseIfNotExist=true
    username: root
    password: Nish@562003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret: your-secret-key-here-must-be-at-least-256-bits-long
      expiration: 86400000 # 24 hours

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  file:
    name: logs/login-service.log
  level:
    root: DEBUG
    com.shopease: DEBUG 